

platform:ios,'8.0'
 
target 'TestTakePrivateDemo' do
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'FMDB'
  pod 'UAObfuscatedString','0.3.2'
pod 'Masonry', '~> 1.1.0'
end
