/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, September 20, 2017 at 9:28:02 PM Eastern European Summer Time
* Operating System: Version 11.0 (Build 15A372)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class SSXPCConnection;

@interface SSSoftwareLibrary : NSObject {

	SSXPCConnection* _connection;

}
-(id)init;
-(void)_sendDemotionMessage:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)_getItemsWithMessage:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)demoteApplicationWithBundleIdentifier:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)hasDemotedApplicationsWithCompletionBlock:(/*^block*/ id)arg1 ;
-(void)isInstalledApplicationWithBundleIdentifier:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)refreshReceiptsWithCompletionBlock:(/*^block*/ id)arg1 ;
-(void)restoreAllDemotedApplicationsWithOptions:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)restoreDemotedApplicationWithBundleIdentifier:(id)arg1 options:(id)arg2 completionBlock:(/*^block*/ id)arg3 ;
-(void)getRemovableSytemApplicationsWithCompletionBlock:(/*^block*/ id)arg1 ;
-(void)getLibraryItemsForITunesStoreItemIdentifiers:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)playableApplicationsWithBundleIdentifiers:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)getLibraryItemForBundleIdentifiers:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)isRemovedSystemApplicationWithBundleIdentifier:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
-(void)restoreRemovedSystemApplicationWithBundleIdentifier:(id)arg1 completionBlock:(/*^block*/ id)arg2 ;
@end

