platform:ios,'9.0'
 
target 'test-002' do
  use_frameworks!
  pod 'Swifter', '~> 1.3.3'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.4'
  pod 'CryptoSwift'
  pod 'UAObfuscatedString','0.3.2'
  pod 'SwiftyRSA'
  #pod 'WechatOpenSDK'
  pod 'JPush'
  pod 'UMengAnalytics'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/WeChat'
pod 'Masonry', '~> 1.1.0'
end
